WIP edits
terraform-ibm-modules/terraform-ibm-watsonx-saas-da pull request #31
Opened 2024-04-18 01:42 UTC by hlucey

This PR is a WIP, please keep it open. Thanks!

2024-04-18 01:44 UTC, hlucey commented
Readme Q: 

1. Line 135: What does this mean? 
> The name to be used on all Watson resources as prefix
 
2. Mentions of Terraform IBM-Cloud/ibm provider? Can this be rewritten to Terraform IBM Cloud and IBM providers?
 
3. Are there any other prefix limitations (For example, prefix must begin and end with a letter and contain only letters, numbers, and - characters.)

2024-04-18 05:05 UTC, andreainnocenti requested changes

2024-04-18 05:05 UTC, andreainnocenti commented on variables.tf
> +    error_message = "The resource plan you use must be free-v1 or professional-v1"
```suggestion
    error_message = "The resource plan you use must be free-v1 or professional-v1."
```

2024-04-18 05:05 UTC, andreainnocenti commented on variables.tf
> +  description = "The name to be used on all Watson resource as prefix"
```suggestion
  description = "The name to be used on all Watson resource as prefix."
```

2024-04-18 05:05 UTC, andreainnocenti commented on README.md
> +| <a name="input_watson_studio_plan"></a> [watson\_studio\_plan](#input\_watson\_studio\_plan) | The resource plan used to provision the Watson Studio instance. | `string` | `"professional-v1"` | no
This documentation is automatically generated according to the `variables.tf` file. We should not modify anything manually here.

2024-04-18 05:05 UTC, andreainnocenti commented on README.md
> +- Provisioning the follwoing services:
```suggestion
- Provisioning the following services:
```

2024-04-18 09:31 UTC, mkrudele requested changes
- Consider that there are sections of the readme that are automatically generated based on the variables.tf and outputs.tf, so you don’t need to update the related sections (doesn’t hurt, the sections will be simply overridden).  
- I saw you used entities in the README like `{{site.data.keyword.Bluemix_notm}}`. They are not rendered in the git repo, so perhaps we should not use in the README!? Not sure if they will be rendered in the conole catalog pages.  
- Would you mind to also edit the outputs.tf file?  
- Would you mind to also edit the nested modules `configure_project` and `configure_user` (same, variables.tf and outputs.tf)?  

Thanks, content looks much better now!!

2024-04-19 21:53 UTC, mkrudele commented
/run pipeline

2024-04-22 10:56 UTC, mkrudele commented
/run pipeline

2024-04-23 12:14 UTC, mkrudele approved these changes

2024-04-24 08:16 UTC, mkrudele commented
/run pipeline

2024-04-24 08:16 UTC, mkrudele submitted a review, later dismissed

2024-04-24 12:29 UTC, mkrudele commented
/run pipeline

2024-04-24 12:30 UTC, mkrudele submitted a review, later dismissed

2024-04-24 12:51 UTC, mkrudele commented
/run pipeline

2024-04-24 12:52 UTC, mkrudele approved these changes

2024-04-24 13:46 UTC, andreainnocenti approved these changes

2024-04-24 13:47 UTC, merged

2024-04-24 13:47 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 0.4.4 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/releases/tag/v0.4.4)
- `v0.4.4`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: