Output edits: WIP Do not merge
terraform-ibm-modules/terraform-ibm-watsonx-saas-da pull request #42
Opened 2024-04-24 16:19 UTC by hlucey

This is a work in progress. Do not merge yet, thanks!

2024-04-24 20:46 UTC, hlucey commented
Variable.tf comments: 

1. Can we make sure that all the variables of the same name use the updated description

2. The descriptions for the input variables don't offer much information and might be more useful if they had links to the docs for the underlying services. For example, the tag description,should we link to the watsonx docs that give some context about tags in watsonx projects or here: https://dataplatform.cloud.ibm.com/docs/content/wsj/getting-started/assets.html?context=wx&audience=wdp#prop-data

3. Are the limitations or additional context for any of the values? For example... "The list can be up to 255 characters and can contain spaces, letters, numbers, underscores, dashes, and the symbols # and @."

4. Variable "ibmcloud_api_key" description = "The API key that's used with the Terraform IBM Cloud and IBM provider."
What does this description mean…?

5. Variable "resource_prefix":  Can you explain what this is? The description is a little confusing.

2024-04-29 13:26 UTC, mkrudele commented
/run pipeline

2024-04-29 13:44 UTC, mkrudele requested changes

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the WatsonX Assistant instance."
Should be `The CRN of the ...`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the WatsonX Assistant instance."
Should be `The name of the...`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the WatsonX Assistant instance."
Should be `The ID of the watson... service plan`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the WatsonX Discovery instance."
Should be `The CRN of..`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the WatsonX Discovery instance."
Should be `the name of ...`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the WatsonX Discovery instance."
Should be `the watsonx... service plan id`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the Watson Machine Learning instance."
Should be `the CRN of ...`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the Watson Machine Learning instance."
Should be `the name of ...`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the Watson Machine Learning instance."
Should be `the watson ... service plan id`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the Watson Studio instance."
Should be `the CRN of ...`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the Watson Studio instance."
Shuld be `the name of ...`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the Watson Studio instance."
Should be `the watson studio.. service plan id`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the Watson Governance instance."
Should be `the CRN of ...`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the Watson Governance instance."
Should be `the name of...`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the Watson Governance instance."
Should be `the watson gove... service plan id`

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "ID of the Watson project."
The ID of the Watsonx project

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "Location of the Watson project."
watsonx project

2024-04-29 13:44 UTC, mkrudele commented on ibm_catalog.json
> +              "description": "URL of the Watson project."
watsonx project

2024-04-29 13:44 UTC, mkrudele commented on outputs.tf
> +  description = "The endpoint of the Watson platform."
watsonx platform

2024-04-29 13:44 UTC, mkrudele commented on variables.tf
> +  description = "The API key that's used with the IBM Cloud Terraform and IBM provider."
Should be `the IBM Cloud Terraform IBM provider`

2024-04-29 13:44 UTC, mkrudele commented on variables.tf
> +  description = "The API key that's used to call Watson APIs to configure the user and the project."
We should provide a more user friendly description. Remove reference to an api call. Something like:  
`The API key of the IBM watsonx admin in the target account`

2024-04-29 13:44 UTC, mkrudele commented on variables.tf
> +  description = "The location that's used with the IBM Cloud Terraform and IBM provider. It's also used during resource creation."
Should be `IBM Cloud Terraform IBM provider`

2024-04-29 14:10 UTC, mkrudele approved these changes

2024-04-29 14:10 UTC, mkrudele commented
/run pipeline

2024-04-29 14:23 UTC, andreainnocenti approved these changes

2024-04-29 14:30 UTC, merged

2024-04-29 18:00 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 0.5.1 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/releases/tag/v0.5.1)
- `v0.5.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: