added storage delegation feature
terraform-ibm-modules/terraform-ibm-watsonx-saas-da pull request #83
Opened 2024-06-06 15:49 UTC by andreainnocenti

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-06-06 16:14 UTC, mkrudele requested changes

2024-06-06 16:14 UTC, mkrudele commented on storage_delegation/variables.tf
> +  description = "This GUID is the globally unique identifier for the Cloud Object Storage instance."
Change to "The globally unique identifier of the Cloud Object Storage instance."

2024-06-06 16:14 UTC, mkrudele commented on storage_delegation/variables.tf
> +  description = "Key Protect CRN used to encrypt the COS bucket used by the Watson project."
Change to "Key Protect service instance CRN used to encrypt the COS buckets used by the watsonx projects."

There can be more than one project using the same cos instance.

2024-06-06 16:14 UTC, mkrudele commented on storage_delegation/variables.tf
> +  description = "Key Protect key CRN used to encrypt the COS bucket used by the Watson project."
Change to: "Key Protect key CRN used to encrypt the COS buckets used by the watsonx projects. If not set, then the cos_kms_new_key_name must be specified."

2024-06-06 16:14 UTC, mkrudele commented on storage_delegation/variables.tf
> +  description = "Name of the Key Protect key to create to encrypt the COS bucket used by the Watson project."
Change to "Name of the Key Protect key to create for encrypting the COS buckets used by the watsonx projects."

2024-06-06 16:14 UTC, mkrudele commented on storage_delegation/variables.tf
> +  description = "The ID of the KMS ring to create the cos_kms_new_key_name into. The parameter will only be used if the DA has to create the KMS key. If it is not set, then the new key will be create
Change to "The identifier of the Key Protect ring to create the cos_kms_new_key_name into. If it is not set, then the new key will be created in the default ring."

2024-06-06 16:14 UTC, mkrudele commented on variables.tf
> +
Change the descriptions accordingly with the changes made to the module.

2024-06-07 04:30 UTC, andreainnocenti commented on configure_project/variables.tf
> +  description = "Set to true of the COS instance is delegated by the account admin."
fixed

2024-06-07 04:32 UTC, andreainnocenti commented on main.tf
> +  watsonx_admin_api_key = var.watsonx_admin_api_key == null || var.watsonx_admin_api_key == "" ? var.ibmcloud_api_key : var.watsonx_admin_api_key
I used the same current logic: 

if the admin apikey is null or empty -> use the deployer apikey
if the admin apikey is passed -> use the admin apikey

2024-06-07 09:05 UTC, andreainnocenti commented on main.tf
> +  watsonx_admin_api_key = var.watsonx_admin_api_key == null || var.watsonx_admin_api_key == "" ? var.ibmcloud_api_key : var.watsonx_admin_api_key
fixed

2024-06-07 09:05 UTC, andreainnocenti commented on storage_delegation/variables.tf
> +variable "watsonx_admin_api_key" {
fixed

2024-06-07 14:42 UTC, andreainnocenti commented
/run pipeline

2024-06-07 14:48 UTC, andreainnocenti commented
/run pipeline

2024-06-07 22:14 UTC, mkrudele commented
/run pipeline

2024-06-08 05:22 UTC, andreainnocenti commented
/run pipeline

2024-06-09 06:32 UTC, andreainnocenti commented
/run pipeline

2024-06-10 06:42 UTC, andreainnocenti commented
/run pipeline

2024-06-10 06:43 UTC, andreainnocenti commented
/run pipeline

2024-06-10 08:23 UTC, andreainnocenti commented
/run pipeline

2024-06-10 08:25 UTC, mkrudele approved these changes

2024-06-10 08:45 UTC, merged